[package]
name = "hakana-language-server"
version = "0.1.0"
edition = "2021"

[dependencies]
hakana-workhorse = { path = "../file_scanner_analyzer" }
hakana-analyzer = { path = "../analyzer" }
hakana-reflection-info = { path = "../code_info" }
tower-lsp = "0.19.0"
tokio = { version = "1.26.0", features = ["full"] }

[lib]
path = "lib.rs"