[package]
name = "hakana-default"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[[bin]]
name = "hakana-lsp"
path = "src/lsp.rs"

[[bin]]
name = "hakana"
path = "src/main.rs"

[dependencies]
hakana-cli = { path = "src/cli" }
hakana-analyzer = { path = "src/analyzer" }
hakana-language-server = { path = "src/language_server" }
mimalloc = { version = "*", default-features = false }
tokio = "1.26.0"
tower-lsp = "0.19.0"

[profile.release]
debug = true

[build-dependencies]
anyhow = { version = "1.0", default-features = false }
vergen = "6"
