[package]
name = "hakana-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
hakana-workhorse = { path = "../file_scanner_analyzer" }
hakana-analyzer = { path = "../analyzer" }
hakana-reflection-info = { path = "../code_info" }
walkdir = "2"
clap = { version = "3.2.6", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
indexmap = "1.8.0"
serde_json = "1.0"
rustc-hash = "1.1.0"

[lib]
path = "lib.rs"