[package]
name = "hakana-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
hakana-workhorse = { path = "../file_scanner_analyzer" }
hakana-analyzer = { path = "../analyzer" }
hakana-reflection-info = { path = "../code_info" }
walkdir = "2"
clap = { version = "3.2.6", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
indexmap = "1.8.0"
serde_json = "1.0"
rustc-hash = "1.1.0"
tower-lsp = "0.19.0"
tokio = { version = "1.26.0", features = ["full"] }
rand = "0.8.5"
rand_chacha = "0.3.1"

[lib]
path = "lib.rs"