name: Rust

on:
  push:
    branches: [ "main" ]
    paths: ['src/**', 'tests/**', 'third-party/**', 'Cargo.toml', 'build.rs', 'init.sh']

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build WASM
      run: ./init.sh && cd src/js_interop/www && npm install && wasm-pack build
